print("Getting information from users")
x=input("enter your name")
print("My name is:",x)
y=input("enter your age")
print("My age is:",y)
z=input("enter your favourite sport")
print("My most liked sport is:",z)
w=input("enter your favourite colour")
print("My favourite colour:",w)
v=input("favourite food")
print("I love eating:",v)
t=input("what are your hobbies")
print("My hobbies are:",t)
q=input("school's name")
print("My school's name is:",q)
k=input("favourite subject")
print("My favourite subject is:",k)
l=input("least favourite subject")
print("My least favourite subject is:",l)
g=input("what do you want to become when you grow up")
print("I want to become a:",g)